// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#include <stdint.h>

#define STRIDE2PAD1_OUT_CH 1
#define STRIDE2PAD1_IN_CH 1
#define STRIDE2PAD1_INPUT_W 7
#define STRIDE2PAD1_INPUT_H 7
#define STRIDE2PAD1_DST_SIZE 16
#define STRIDE2PAD1_INPUT_SIZE 49
#define STRIDE2PAD1_OUT_ACTIVATION_MIN -128
#define STRIDE2PAD1_OUT_ACTIVATION_MAX 127
#define STRIDE2PAD1_INPUT_BATCHES 1
#define STRIDE2PAD1_FILTER_X 3
#define STRIDE2PAD1_FILTER_Y 3
#define STRIDE2PAD1_STRIDE_X 2
#define STRIDE2PAD1_STRIDE_Y 2
#define STRIDE2PAD1_PAD_X 1
#define STRIDE2PAD1_PAD_Y 1
#define STRIDE2PAD1_OUTPUT_W 4
#define STRIDE2PAD1_OUTPUT_H 4
#define STRIDE2PAD1_INPUT_OFFSET 128
#define STRIDE2PAD1_OUTPUT_OFFSET -20
#define STRIDE2PAD1_DILATION_X 1
#define STRIDE2PAD1_DILATION_Y 1

const int32_t stride2pad1_biases[1] = {-9794};

const int8_t stride2pad1_weights[9] = {-54, 57, -19, -127, 87, 70, 74, -110, 66};

const int8_t stride2pad1_input[49] = {-91, -30,  -57, -76, 32,   -13, 14,  -96,  108, -4,  41, 48,  107,
                                      -68, -101, 30,  95,  95,   91,  -66, -80,  114, -49, 7,  -67, -35,
                                      -1,  -88,  -77, -56, -103, 5,   -39, -118, -24, -32, 67, 11,  38,
                                      -16, -124, 44,  -46, -92,  -24, 108, 80,   -29, -3};
                                
const int8_t stride2pad1_output_ref[16] = {26, -11, 33, -25, -96, -52, -78, -86, 33, -2, -88, -113, -14, 0, -84, -27};

const int32_t stride2pad1_output_mult[1] = {2033801520};

const int32_t stride2pad1_output_shift[1] = {-8};
