// Generated by generate_test_data.py using TFL version 2.6.0 as reference.

#include <stdint.h>
#define MAXPOOLING_2_OUT_CH 5
#define MAXPOOLING_2_IN_CH 5
#define MAXPOOLING_2_INPUT_W 12
#define MAXPOOLING_2_INPUT_H 1
#define MAXPOOLING_2_DST_SIZE 60
#define MAXPOOLING_2_INPUT_SIZE 60
#define MAXPOOLING_2_OUT_ACTIVATION_MIN -128
#define MAXPOOLING_2_OUT_ACTIVATION_MAX 127
#define MAXPOOLING_2_INPUT_BATCHES 1
#define MAXPOOLING_2_FILTER_X 3
#define MAXPOOLING_2_FILTER_Y 1
#define MAXPOOLING_2_STRIDE_X 1
#define MAXPOOLING_2_STRIDE_Y 2
#define MAXPOOLING_2_PAD_X 1
#define MAXPOOLING_2_PAD_Y 0
#define MAXPOOLING_2_OUTPUT_W 12
#define MAXPOOLING_2_OUTPUT_H 1

const int8_t maxpooling_2_input[60] = {75,  -52,  -42,  -30, 56,  64,   106, -36, 120, -3,  34,   -105, 69,   75,  -39,
                                       15,  93,   -71,  39,  34,  -11,  65,  22,  59,  106, 105,  45,   -116, -75, 123,
                                       -65, 75,   -61,  13,  -25, -123, 59,  110, -65, 86,  -108, -107, -17,  38,  27,
                                       -1,  -115, -123, 75,  -75, 68,   52,  12,  -35, 116, -68,  22,   15,   76,  -81};

const int8_t maxpooling_2_output_ref[60] = {75,  106, -36, 120, 56,  75,  106, 69,  120, 56,  64,  106, 69,  120, 34,
                                            34,  93,  69,  75,  106, 105, 93,  22,  59,  123, 105, 75,  22,  59,  123,
                                            105, 75,  110, 13,  123, -65, 75,  110, 38,  86,  -1,  59,  110, 75,  86,
                                            68,  52,  12,  75,  116, 68,  52,  15,  76,  116, 68,  52,  15,  76,  116};
